const express = require('express');
const router = express.Router();
let Hotels = require('./hiltonDerbyHotels');

let hiltonList = [
  'Hampton Inn Twin Falls',
  'Hilton Garden Inn Twin Falls',
  'Hilton Ponce Golf & Casino Resort',
  'Hampton Inn & Suites San Juan',
  'DoubleTree by Hilton Hotel Portland, ME',
  'The Higgins Hotel New Orleans, Curio Collection by Hilton',
  'Boulders Resort & Spa Scottsdale, Curio Collection by Hilton',
  'Hilton Grand Vacations at the Flamingo',
  'Double tree by hilton hotel billings',
  'Double tree by Hilton Niagara Falls',
  'Hilton Habtoor City',
  'Double Tree by hilton Atlantic Beach',
  'Home2 Suites by Hilton Las Cruces',
  'hilton darwin',
  'Hilton Colon Quito',
  'Hilton Garden Inn Waikiki Beach ',
  'Hilton Garden Inn Denver Airport',
  'Hilton Garden Inn Denver Downtown',
  'DoubleTree by Hilton Hotel Durango',
  'Hampton Inn St Louis Downtown (At the Gateway Arch)',
  'Hampton Inn Bennington',
  'Hoodoo Moab, Curio Collection by Hilton',
  'DoubleTree Suites by Hilton Hotel Doheny Beach',
  'Cliffrose Springdale, Curio Collection by Hilton',
  'Hilton Playa del Carmen',
  'Hilton La Romana Adult Resort',
  'hilton tampa downtown',
  'Homewood Suites by Hilton Joplin',
  'Homewood Suites by Hilton Paducah',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'Hilton Garden Inn New York Central Park',
  'Hampton Inn Idaho Falls',
  'Pointe Hilton Squaw Peak Resort',
  'hampton inn and suites barstow',
  'Hilton Garden Inn San Luis Obispo/Pismo Beach',
  'Hotel Don Fernando de Taos, Tapestry Collection by Hilton',
  'Hilton Atlanta/Marietta Hotel & Conference Center',
  'Hilton Garden Inn Providence',
  'hampton inn and suites watertown',
  'Hilton Anchorage',
  'Hilton Aruba Caribbean Resort & Casino',
  'Homewood Suites by Hilton Houma',
  'Hampton Inn Downtown',
  'hampton Inn & Suites homestead',
  'Hampton Inn & Suites Kingman',
  'Hilton Newark Airport, Spring Street, Elizabeth, NJ, USA',
  'Hilton Marco Island Beach Resort and Spa',
  'Miramonte Indian Wells Resort & Spa, Curio Collection by Hilton, Indian Wells Lane, Indian Wells, CA, USA',
  'Miramonte Indian Wells Resort & Spa, Curio Collection by Hilton, Indian Wells Lane, Indian Wells, CA, USA',
  'DoubleTree by Hilton Hotel Claremont',
  'DoubleTree by Hilton Hotel Berkeley Marina',
  'Hampton Inn Manhattan-Chelsea',
  'DoubleTree by Hilton Hotel New York City',
  'Hilton Garden Inn Atlanta Downtown',
  'Hampton Inn & Suites San Luis Obispo, Calle Joaquin, San Luis Obispo, CA, USA',
  'Hilton Garden Inn Napa, Solano Avenue, Napa, CA, USA',
  'Hampton Inn Grand Junction Downtown/Historic Main Street, Main Street, Grand Junction, CO, USA',
  'Hilton Cabana Miami Beach ',
  'Hilton Ocean City Oceanfront Suites',
  'Hilton Asheville Biltmore Park',
  'Hilton La Romana Family Resort',
  'DoubleTree by Hilton Hotel Olympia',
  'DoubleTree by Hilton Hotel Orlando East-UCF Area, High Tech Avenue, Orlando, FL, USA',
  'Hilton Garden Inn San Diego Old Town/SeaWorld Area',
  'DoubleTree Suites by Hilton',
  'Hilton Fort Worth, Main Street, Fort Worth, TX, USA',
  'HHHWI The Westin Hilton Head Island Resort & Spa',
  'DoubleTree by Hilton Hotel New York Times Square West',
  'Hilton Garden Inn Fort Walton Beach, Miracle Strip Parkway Southeast, Fort Walton Beach, FL, USA',
  'Hilton Sandestin Beach Golf Resort & Spa, South Sandestin Boulevard, Miramar Beach, FL, USA',
  'Hilton Cleveland Downtown, Lakeside Avenue East, Cleveland, OH, USA',
  'DoubleTree Suites by Hilton Hotel Santa Monica, 4th Street, Santa Monica, CA, USA',
  'The Hacienda at Hilton Puerto Vallarta All Inclusive Adults Only',
  'Hampton Inn Monterrey Aeropuerto',
  'Hilton Minneapolis',
  'Hilton San Diego Gaslamp Quarter',
  'Homewood Suites by Hilton San Diego Downtown',
  'Hilton Garden Inn San Diego Downtown/Bayside',
  'Hampton Inn Manhattan/Times Square Central',
  'Hampton Inn & Suites by Hilton Los Cabos',
  'Ocean Tower at Hilton Waikoloa Village Asia',
  'Hilton Garden Inn Denver Airport',
  'Hampton Inn Las Vegas/North Speedway',
  'Hampton Inn and Suites Las Vegas/West Summerlin',
  'Hampton Inn Las Vegas/Summerlin',
  'Hilton Grand Vacations on Paradise',
  'Hampton Inn Tropicana',
  'Hampton Inn and Suites Las Vegas Airport',
  'Embassy Suites by Hilton Las Vegas',
  'DoubleTree by Hilton Las Vegas Airport',
  'Embassy Suites by Hilton Convention Center Las Vegas',
  'Homewood Suites by Hilton Las Vegas Airport',
  'Hampton Inn and Suites Henderson/Saint Rose',
  'Homewood Suites by Hilton Henderson/South Las Vegas',
  'Hampton Inn and Suites Henderson',
  'Hilton Garden Inn Las Vegas/Henderson',
  'Homewood Suites by Hilton Miami Downtown/Brickell',
  'Hilton Garden Inn Valencia Six Flags',
  'DoubleTree by Hilton Hotel Bakersfield',
  'Embassy Suites by Hilton Phoenix Scottsdale',
  'Hilton Garden Inn Dallas Downtown',
  'Hilton Garden Inn New York Times Square South',
  'El Conquistador Tucson, A Hilton Resort',
  'DoubleTree by Hilton Hotel Golf Resort Palm Springs',
  'McLean/DoubleTree by Hilton',
  'DoubleTree by Hilton Nashua',
  'Hilton San Diego Airport-Harbor Island',
  'The Darcy, Curio Collection by Hilton',
  'Homewood Suites by Hilton New Orleans French Quarter',
  'Hilton Cabana Miami Beach',
  'Condado Lagoon Villas at Caribe Hilton',
  'Hilton Garden Inn Miami South Beach',
  'Hilton Mexico City Reforma',
  'Hilton Puerto Vallarta Resort',
  'Hilton Garden Inn Redondo Beach',
  'GALLERYone - a DoubleTree Suites by Hilton Hotel',
  'The Gates Hotel South Beach - A DoubleTree By Hilton',
  'Doubletree by Hilton Orlando at SeaWorld',
  'Hampton Inn International Dr Convention Center',
  'Hilton Boston Downtown-Faneuil Hall',
  'DoubleTree by Hilton Bethesda-Washington D.C.',
  'DoubleTree by Hilton Hotel Portland, ME',
  'Hilton Garden Inn New York/Tribeca',
  'Hilton Garden Inn New York/West 35th Street',
  'Hampton Inn Manhattan-Chelsea',
  'Hampton Inn Manhattan-35th St/Empire State Bldg',
  'Hampton Inn Manhattan-Seaport-Financial District',
  'DoubleTree by Hilton Hotel New York City - Chelsea',
  'Hampton Inn Manhattan Grand Central',
  'Hilton Garden Inn New York/Central Park South-Midtown West',
  'Hampton Inn Manhattan-Times Square North',
  'Hilton Garden Inn New York/Manhattan-Midtown East',
  'DoubleTree by Hilton Hotel New York - Times Square South',
  'Hampton Inn Manhattan-SoHo',
  'DoubleTree by Hilton Cape Cod - Hyannis',
  'Hilton Garden Inn Austin Downtown',
  'Hilton Garden Inn Times Square',
  'Hampton Inn Madison Square Garden',
  'Hilton Newark Penn Station ',
  'The Wit Chicago a Doubletree by Hilton',
  'DoubleTree by Hilton Del Mar',
  'Hilton Orange County',
  'Doubletree by Hilton Irvine Spectrum',
  'DoubleTree by Hilton Santa Ana Orange County Airport',
  'Hilton Phoenix Mesa',
  'Hilton Waikoloa Village Asia',
  'Hilton Marco Island Beach Resort and Spa',
  'Hilton Santa Barbara Beachfront Resort',
  'Hilton Garden Inn Carlsbad Beach',
  'Hilton Palm Springs',
  'Hilton Santa Fe at Buffalo Thunder',
  'Hilton Garden Inn Orlando International Drive North',
  'Doubletree by Hilton Fresno Convention Center',
  'Cape Rey Carlsbad, A Hilton Resort',
  'Hilton Garden Inn New York Chelsea',
  'DoubleTree by Hilton Greenway Plaza',
  'DoubleTree by Hilton Hotel Anaheim - Orange County',
  'DoubleTree by Hilton Tucson at Reid Park',
  'Hampton Inn Downtown French-Quarter Area',
  'DoubleTree by Hilton San Pedro - Port of Los Angeles',
  'Hilton Portland Downtown',
  'DoubleTree by Hilton Hotel Grand Junction',
  'Hilton Singer Island Oceanfront Palm Beaches',
  'DoubleTree by Hilton San Diego Mission Valley',
  'Doubletree by Hilton Deerfield Beach-Boca Raton',
  'Hampton Inn and Suites Convention Center ',
  'Homewood Suites by Hilton North Happy Valley',
  'Hilton Orlando Altamonte Springs',
  'Hilton Santa Cruz Scotts Valley',
  'DoubleTree by Hilton San Francisco Airport North',
  'Hilton Galveston Island Resort',
  'The Waterfront Beach Resort, a Hilton Hotel',
  'Hilton Garden Inn Waikiki Beach',
  'DoubleTree Suites by Hilton Santa Monica',
  'The Curtis - A Doubletree By Hilton',
  'Doubletree by Hilton Sonoma Wine Country',
  'Millennium Hilton New York One UN Plaza',
  'Hilton Anchorage',
  'DoubleTree Beach Resort by Hilton Tampa Bay',
  'Homewood Suites by Hilton Nearest Universal Orlando',
  'Pointe Hilton Tapatio Cliffs Resort',
  'Pointe Hilton Squaw Peak Resort',
  'Doubletree by Hilton Hotel Circle',
  'Caribe Hilton',
  'Doubletree by Hilton Hotel Baton Rouge',
  'Hilton Garden Inn New Orleans French Quarter',
  'Hilton Fort Worth ',
  'Hilton Miami Downtown',
  'Hilton Minneapolis St. Paul Airport',
  'Bahia Mar Fort Lauderdale Beach - a DoubleTree by Hilton',
  'Hilton Sonoma Wine Country',
  'Condado Plaza Hilton',
  'Millennium Hilton New York Downtown',
  'DoubleTree Resort by Hilton Hollywood Beach',
  'Westgate New York City, formerly Hilton New York Grand Central',
  'Hilton Chicago Ohare Airport',
  'Hilton West Palm Beach, Okeechobee Boulevard, West Palm Beach, FL, USA',
  'Pointe Hilton Tapatio Cliffs Resort, North 7th Street, Phoenix, AZ, USA',
  'Hilton Santa Barbara Beachfront Resort, East Cabrillo Boulevard, Santa Barbara, CA, USA',
  'Hilton Hua Hin Resort & Spa, Naresdamri Road Hua Hin, Hua Hin District, Prachuap Khiri Khan, Thailand',
  'Mahogany Bay Resort & Beach Club, Curio Collection by Hilton, San Pedro Ambergris C, Belize',
  'Hilton new york fashion districk ',
  'Embassy Suites by Hilton Napa Valley, California Boulevard, Napa, CA, USA',
  'Hampton Inn & Suites Lady Lake/The Villages, Northeast 63rd Drive, Lady Lake, FL, USA',
  'Hilton Grand Vacations at Tuscany Village, Arrezzo Way, Orlando, FL, USA',
  'Hilton Burlington, Battery Street, Burlington, VT, USA',
  'Hilton San Diego Bayfront, Park Boulevard, San Diego, CA, USA',
  'The Art Hotel Denver, Curio Collection by Hilton',
  'LondonHouse Chicago, Curio Collection by Hilton, East Upper Wacker Drive, Chicago, IL, USA',
  'Homewood Suites by Hilton Moab',
  'Inn and Club at Harbour Town, Lighthouse Lane, Hilton Head Island, SC, USA',
  'Grand Naniloa Hotel Hilo - a DoubleTree by Hilton, Banyan Drive, Hilo, HI, USA',
  'DoubleTree by Hilton Hotel Memphis Downtown, Union Avenue, Downtown, Memphis, TN, USA',
  'The Park Vista - a DoubleTree by Hilton Hotel',
  'Hampton Inn Cheyenne, Fleischli Parkway, Cheyenne, WY, USA',
  'Hilton Garden Inn Rapid City, East Mall Drive, Rapid City, SD, USA',
  'Hilton Guam Resort & Spa',
  'Hilton Guam Resort & Spa',
  'Protea Hotel by Marriott Hilton',
  'Hampton Inn, Norman Rd, Bar Harbor, ME, USA',
  'Hilton Garden Inn Kauai Wailua Bay, Kuhio Highway, Kapaa, HI, USA',
  'Hilton Lake Las Vegas Resort & Spa',
  'Hilton Garden Inn Portland Downtown Waterfront, Commercial Street, Portland, ME, United States',
  'DoubleTree by Hilton Hotel & Spa Napa Valley',
  'Hampton Inn & Suites Pocatello, Vista Drive, Pocatello, ID, United States',
  'Hampton Inn Jackson Hole, U.S. 89, Jackson, WY, United States',
  'DoubleTree Suites by Hilton Hotel Boston-Cambridge, Soldiers Field Road, Boston, MA, United States',
  'Hampton Inn Cocoa Beach/Cape Canaveral, North Atlantic Avenue, Cocoa Beach, FL, United States',
  'Hampton Inn Durango, Main Avenue, Durango, CO, United States',
  'Home2 Suites by Hilton Amarillo, West Amarillo Boulevard, Amarillo, TX, United States',
  'Hampton Inn Clinton, Kansas Avenue, Clinton, MO, United States',
  'Holiday Inn Express Hilton Head Island',
  'DoubleTree by Hilton Hotel Woking',
  'DoubleTree by Hilton Hotel Alice Springs',
  'DoubleTree by Hilton Vail',
  'DoubleTree by Hilton Hotel Darwin',
  'Hilton Garden Inn Dalton',
  'DoubleTree by Hilton Hotel Decatur Riverfront',
  'DoubleTree by Hilton Hotel Cairns',
  'Candlewood Suites Bluffton-Hilton Head',
  'Homewood Suites by Hilton Montgomery EastChase',
  'Homewood Suites by Hilton Jacksonville Deerwood Park',
  'Homewood Suites by Hilton Eatontown',
  'DoubleTree by Hilton Hotel Galveston Beach',
  'Hilton Nashville Airport',
  'DoubleTree by Hilton Atlanta Perimeter Dunwoody',
  'DoubleTree by Hilton Hotel Santa Fe',
  'DoubleTree by Hilton Hotel Schenectady',
  'Homewood Suites by Hilton Aurora Naperville',
  'Sonesta Resort Hilton Head Island',
  'Embassy Suites by Hilton West Palm Beach Central',
  'DoubleTree by Hilton Hotel Buffalo - Amherst',
  'DoubleTree by Hilton Halifax Dartmouth',
  'The Campbell House, Curio Collection by Hilton a',
  'DoubleTree by Hilton Hotel Jacksonville Riverfront a',
  'DoubleTree by Hilton Hotel Sunrise - Sawgrass Mills',
  'Hampton Inn Chicago Downtown/Magnificent Mile',
  'DoubleTree by Hilton Boston North Shore',
  'DoubleTree by Hilton Hotel Billings',
  'DoubleTree by Hilton Hotel Minneapolis North',
  'DoubleTree by Hilton Hotel Pittsburgh - Meadow Lands',
  'DoubleTree by Hilton Hotel Laurel',
  'DoubleTree by Hilton Mount Vernon',
  'DoubleTree by Hilton Hotel Lawrence',
  'DoubleTree by Hilton Hotel Richmond - Midlothian',
  'Hampton Inn Salem',
  'DoubleTree by Hilton Hotel Boston - Rockland',
  'DoubleTree by Hilton Hotel Raleigh - Brownstone - University',
  'DoubleTree by Hilton Hotel Winston Salem - University',
  'Holiday Inn Resort Beach House Hilton Head Island',
  'DoubleTree by Hilton Helena Downtown',
  'DoubleTree by Hilton Harrisonburg',
  'DoubleTree by Hilton Fort Smith City Center',
  'DoubleTree by Hilton Hotel North Charleston Convention Center',
  'Hampton Inn & Suites Buffalo Downtown',
  'DoubleTree by Hilton Baltimore BWI Airport',
  'Holiday Inn Express & Suites Hardeeville-Hilton Head',
  'Hampton Inn Covington',
  'Holiday Inn Express & Suites Bluffton @ Hilton Head Area',
  'Hilton Garden Inn Minneapolis Airport Mall of America',
  'Hilton Garden Inn San Diego Mission Valley Stadium',
  'DoubleTree by Hilton Hotel Orlando East-UCF Area',
  'DoubleTree by Hilton Hotel Orlando Airport',
  'Hilton Seychelles Labriz Resort & Spa, Silhouette, Seychelles',
  'Embassy Suites by Hilton Deerfield Beach Resort & Spa, South Ocean Drive, Deerfield Beach, FL, United States',
  'Hampton Inn & Suites Napa, Napa Valley, Hartle Court, Napa, CA, United States',
  'The Inn At Penn A Hilton Hotel',
  'Hilton Garden Inn Portsmouth Downtown, High Street, Portsmouth, NH, United States',
  'Hilton Garden Inn Guatemala City, 13 Calle, Guatemala City, Guatemala',
  'Hampton Inn Montrose, North Townsend Avenue, Montrose, CO, United States',
  'DoubleTree Resort by Hilton Central Pacific',
  'DoubleTree Suites by Hilton Hotel, Broadway, New York, NY, United States',
  'DoubleTree Suites by Hilton Hotel, Broadway, New York, NY, United States',
  'DoubleTree by Hilton Hotel Missoula - Edgewater, Madison Street, Missoula, MT, United States',
  'Hampton Inn & Suites Lake Powell',
  'DoubleTree by Hilton Cocoa Beach Oceanfront, North Atlantic Avenue, Cocoa Beach, FL, United States',
  'DoubleTree by Hilton, North Interstate Highway 35, Austin, TX, United States',
  'Hilton Hawaiian Village Waikiki Beach Resort ',
  'Capital Hilton ',
  'Hilton Garden Inn Mountain View',
  'DoubleTree by Hilton Hotel Jackson, U.S. 45 Bypass, Jackson, TN, United States',
  'Homewood Suites by Hilton Cape Canaveral-Cocoa Beach, Astronaut Boulevard, Cape Canaveral, FL, United States',
  'DoubleTree by Hilton Hotel Lafayette, West Pinhook Road, Lafayette, LA, United States',
  'Hilton Midtown, 6th Avenue, New York, NY, United States',
  'Jewel Dunns River Beach Resort & Spa, Ocho Rios, Curio Collection by Hilton, St. Ann Parish, Jamaica',
  'Doubletree Resort by Hilton Hotel Alana Waikiki Beach',
  'The Highland Dallas, Curio Collection by Hilton',
  'Parc Soleil by Hilton Grand Vacations, Desforges Avenue, Orlando, FL, United States',
  'Homewood Suites by Hilton Charleston',
  'Homewood Suites by Hilton Orlando-Maitland',
  'DoubleTree Suites by Hilton Hotel New York City ',
  'DoubleTree by Hilton Hotel at the Entrance to Universal Orlando',
  'Hilton Garden Inn Bloomington',
  'Hampton Inn & Suites Page - Lake Powell, Page, AZ, United States',
  'The Logan Philadelphia, Curio Collection by Hilton',
  'Hilton at Resorts World Bimini',
  'Hampton Inn Houma',
  'Hilton Garden Inn Clovis',
  'Hilton Garden Inn San Jose La Sabana',
  'Hilton Waikiki Beach, Kuhio Avenue, Honolulu, HI, United States',
  'Double Tree by Hilton Marina del Rey',
  'Hilton Oakland Airport',
  'DoubleTree by Hilton Denver',
  'Hilton Vancouver Airport, Minoru Boulevard, Richmond, BC, Canada',
  'Hampton Inn & Suites Arroyo Grande/Pismo Beach Area, West Branch Street, Arroyo Grande, CA, United States',
  'Homewood Suites by Hilton Kalispell, MT, Hutton Ranch Road, Kalispell, MT, United States',
  'Hilton Garden Inn Augusta',
  'Embassy Suites by Hilton Boca Raton',
  'Hampton Inn Buffalo South/I-90',
  'Hampton Inn & Suites Springdale/Zion National Park',
  'Omni Hilton Head Oceanfront Resort',
  'Hilton Auckland, Quay Street, Auckland, New Zealand',
  'Hilton Garden Inn Flagstaff',
  'Pensacola Beach Hotel Hilton',
  'The Skirvin Hilton',
  'Hilton Garden Inn Lafayette/Cajundome',
  'Doubletree by Hilton Flagstaff',
  'Hilton Garden Inn Oklahoma City Midtown',
  'DoubleTree by Hilton Toronto Downtown',
  'DoubleTree by Hilton Hotel Seattle Airport',
  'Hilton Garden Inn Key West',
  'DoubleTree by Hilton Hotel Bethesda',
  'Hilton Garden Inn Ogden',
  'Hampton Inn Clemson-University Area',
  'DoubleTree by Hilton Hotel Sunrise',
  'Hilton Garden Inn Idaho Falls',
  'Hilton Garden Inn Amarillo',
  'Homewood Suites by Hilton Medford',
  'Hampton Inn & Suites Ridgecrest',
  'London Hilton on Park Lane',
  'Hilton Garden Inn Knoxville/University',
  'Hilton Orlando Buena VIsta Palace',
  'Hilton Pyramids Golf Resort',
  'Doubletree Suites By Hilton Naples',
  'The Fess Parker A Doubletree by Hilton Resort',
  'DoubleTree by Hilton Hotel Dallas - Farmers Branch',
  'Hilton Checkers Los Angeles',
  'DoubleTree by Hilton New York - Financial District',
  'Hampton Inn Dayton/Fairborn',
  'Hampton Inn Manhattan-SoHo',
  'Hilton Garden Inn Los Angeles Hollywood',
  'Hilton Doha',
  'Hilton Jumeirah Resort',
  'Hilton Universal City',
  'Hampton Inn and Suite Rock Springs',
  'Hampton Inn & Suites Plymouth',
  'DoubleTree by Hilton Boston Downtown',
  'Hilton - Naples',
  'Hilton Garden Inn Sarasota',
  'The Quin Central Park by Hilton Club',
  'Hilton Seattle',
  'DoubleTree Resort by Hilton Paradise Valley',
  'Hampton Inn & Suite',
  'Hilton Garden Inn Missoula',
  'Hilton Anaheim',
  'Hilton Grand Vacations Suites at SeaWorld',
  'DoubleTree by Hilton Breckenridge',
  'Hilton Los Angeles Universal City',
  'Hampton Inn Lake Havasu City',
  'Hampton Inn & Suites Natchez',
  'Hampton Inn & Suites Vicksburg',
  'Hilton Garden Inn Chattanooga',
  'DoubleTree by Hilton Hotel JFK Airport',
  'Hilton Rose Hall Resort & Spa',
  'DoubleTree by Hilton Orlando Downtown',
  'Hampton Inn',
  'Hampton Inn',
  'Hilton Portland and Executive Tower',
  'Hilton New York JFK Airport Hotel',
  'Hampton Inn ',
  'Hilton Garden Inn',
  'Hilton Budapest',
  'Hilton Garden Inn Fort Myers',
  'Hampton Inn And Suites Bakersfield',
  'Hilton Niagara Falls/Fallsview',
  'Hilton Garden Inn Eden Prairie',
  'Hampton Inn and Suites Jackson-Coliseum',
  'DoubleTree by Hilton Memphis',
  'Hampton Inn Champaign Urbana',
  'Hilton Dallas Lincoln Centre',
  'Hilton Garden Inn Orlando',
  'Hilton Waikiki Beach',
  'Hilton Grand Vacations Suites on International Drive',
  'Hampton Inn & Suites Flagstaff',
  'Hampton Inn Albuquerque University/Midtown',
  'Hampton Inn Santa Fe',
  'DoubleTree by Hilton Hotel Springfield',
  'Hilton Grand Vacation Suites Las Vegas',
  'Hilton Washington',
  'Hilton Santa Fe Historic Plaza',
  'Hampton Inn Bloomington West',
  'Hilton Fort Lauderdale Marina',
  'Hilton Garden Inn Savannah Historic District',
  'Hilton Orlando Lake Buena Vista',
  'Hilton Hawaiian Village Waikiki Beach Resort',
  'Hilton Boston Back Bay',
  'Hilton Garden Inn Calgary Airport',
  'Hampton Inn & Suites Tarpon Springs',
  'Hampton Inn Okeechobee',
  'Hilton Orlando',
  'Hilton Cincinnati Netherland Plaza',
  'Hilton Parc 55 San Francisco',
  'Hilton Garden Inn Calabasas',
  'Hilton Los Angeles North Glendale',
  'Hilton Quebec',
  'Hilton Mexico City Airport',
  'Molino Stucky Hilton',
  'Hilton Longboat Key Beachfront Resort',
  'Hilton Lac-Leamy',
  'Hilton Garden Inn Billings',
  'Hilton Garden Inn Monterey',
  'Hilton San Diego Resort and Spa',
  'Hilton Key Largo Resort',
  'Hilton Sedona Resort and Spa',
  'Hilton Garden Inn Freeport Downtown',
  'Hilton Woodland Hills Los Angeles',
  'Hilton Woodland Hills Los Angeles',
  'Hilton Houston Plaza / Medical Center',
  'Hilton Fort Collins',
  'Hilton Garden Inn Montreal Centre-Ville',
  'Hilton Montreal Bonaventure',
  'Hampton Inn & Suites Boston Crosstown Center',
  'Hilton Giardini Naxos',
  'Hampton Inn St. Simons Island',
  'Homewood Suites by Hilton Rock Springs',
  'Hilton Garden Inn Bozeman',
  'Hilton Raleigh-Durham Airport',
  'Hilton Boston Logan Airport',
  'Hampton Inn Helena',
  'Hampton Inn Salt Lake City - Downtown',
  'Cliffrose Springdale, Curio Collection by Hilton',
  'Homewood Suites by Hilton Jackson',
  'Signia by Hilton Orlando Bonnet Creek',
  'Hilton Chicago O hare',
  'Hilton Daytona Beach Oceanfront Resort',
  'Hilton Americas Houston',
  'Hampton Inn Lancaster',
  'Hilton Cocoa Beach',
  'Hotel del Coronado, Curio Collection by Hilton',
  'Hilton Vancouver Metrotown',
  'Hilton Fort Lauderdale Beach Resort',
  'Hilton Salt lake City Center',
  'Hilton Boston Financial District',
  'Hilton San Francisco Financial District',
  'Hilton Clearwater Beach Resort',
  'Hilton Las Vegas',
  'Hampton Inn Kayenta',
  'Westin Hilton Head',
  'Hilton Anatole',
  'Hilton La Jolla',
  'Hilton Bentley South Beach',
  'Hilton Los Cabos',
  'Hilton Cancun Golf & Spa Resort',
  'Canoa ( Coral by Hilton )',
  'Marien ( Coral by Hilton )',
  'Hilton Dubai Creek',
  'Hilton Waikoloa Village',
  'Hilton Walt Disney Resort',
  'Hilton San Francisco Union Square',
  'Hilton Times Square',
  'Hilton Los Angeles Airport',
  'Hilton Seychelles Northolme Spa',
  'Hilton Paris Aeroport Orly',
  'Hilton Paris La Defense',
  'Hilton Paris',
  'Hilton Arc de Triomphe',
  'Palmer House Hilton',
  'Hilton Chicago',
  'Millennium Hilton',
  'Hilton New York',
  'British Colonial Hilton',
  'Hilton Mauritius',
  'Hilton Miami Airport',
  'Beverly Hilton',
]
let filteredDashboardHiltonList = [
  'Hampton Inn Twin Falls',
  'Hilton Garden Inn Twin Falls',
  'Hilton Ponce Golf & Casino Resort',
  'Hampton Inn & Suites San Juan',
  'DoubleTree by Hilton Hotel Portland, ME',
  'The Higgins Hotel New Orleans, Curio Collection by Hilton',
  'Boulders Resort & Spa Scottsdale, Curio Collection by Hilton',
  'Hilton Grand Vacations at the Flamingo',
  'Double tree by hilton hotel billings',
  'Double tree by Hilton Niagara Falls',
  'Hilton Habtoor City',
  'Double Tree by hilton Atlantic Beach',
  'Home2 Suites by Hilton Las Cruces',
  'hilton darwin',
  'Hilton Colon Quito',
  'Hilton Garden Inn Waikiki Beach ',
  'Hilton Garden Inn Denver Airport',
  'Hilton Garden Inn Denver Downtown',
  'DoubleTree by Hilton Hotel Durango',
  'Hampton Inn St Louis Downtown (At the Gateway Arch)',
  'Hampton Inn Bennington',
  'Hoodoo Moab, Curio Collection by Hilton',
  'DoubleTree Suites by Hilton Hotel Doheny Beach',
  'Cliffrose Springdale, Curio Collection by Hilton',
  'Hilton Playa del Carmen',
  'Hilton La Romana Adult Resort',
  'hilton tampa downtown',
  'Homewood Suites by Hilton Joplin',
  'Homewood Suites by Hilton Paducah',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'hampton inn bozeman',
  'Hilton Garden Inn New York Central Park',
  'Hampton Inn Idaho Falls',
  'Pointe Hilton Squaw Peak Resort',
  'hampton inn and suites barstow',
  'Hilton Garden Inn San Luis Obispo/Pismo Beach',
  'Hotel Don Fernando de Taos, Tapestry Collection by Hilton',
  'Hilton Atlanta/Marietta Hotel & Conference Center',
  'Hilton Garden Inn Providence',
  'hampton inn and suites watertown',
  'Hilton Anchorage',
  'Hilton Aruba Caribbean Resort & Casino',
  'Homewood Suites by Hilton Houma',
  'Hampton Inn Downtown',
  'hampton Inn & Suites homestead',
  'Hampton Inn & Suites Kingman',
  'Hilton Newark Airport, Spring Street, Elizabeth, NJ, USA',
  'Hilton Marco Island Beach Resort and Spa',
  'Miramonte Indian Wells Resort & Spa, Curio Collection by Hilton, Indian Wells Lane, Indian Wells, CA, USA',
  'Miramonte Indian Wells Resort & Spa, Curio Collection by Hilton, Indian Wells Lane, Indian Wells, CA, USA',
  'DoubleTree by Hilton Hotel Claremont',
  'DoubleTree by Hilton Hotel Berkeley Marina',
  'Hampton Inn Manhattan-Chelsea',
  'DoubleTree by Hilton Hotel New York City',
  'Hilton Garden Inn Atlanta Downtown',
  'Hampton Inn & Suites San Luis Obispo, Calle Joaquin, San Luis Obispo, CA, USA',
  'Hilton Garden Inn Napa, Solano Avenue, Napa, CA, USA',
  'Hampton Inn Grand Junction Downtown/Historic Main Street, Main Street, Grand Junction, CO, USA',
  'Hilton Cabana Miami Beach ',
  'Hilton Ocean City Oceanfront Suites',
  'Hilton Asheville Biltmore Park',
  'Hilton La Romana Family Resort',
  'DoubleTree by Hilton Hotel Olympia',
  'DoubleTree by Hilton Hotel Orlando East-UCF Area, High Tech Avenue, Orlando, FL, USA',
  'Hilton Garden Inn San Diego Old Town/SeaWorld Area',
  'DoubleTree Suites by Hilton',
  'Hilton Fort Worth, Main Street, Fort Worth, TX, USA',
  'HHHWI The Westin Hilton Head Island Resort & Spa',
  'DoubleTree by Hilton Hotel New York Times Square West',
  'Hilton Garden Inn Fort Walton Beach, Miracle Strip Parkway Southeast, Fort Walton Beach, FL, USA',
  'Hilton Sandestin Beach Golf Resort & Spa, South Sandestin Boulevard, Miramar Beach, FL, USA',
  'Hilton Cleveland Downtown, Lakeside Avenue East, Cleveland, OH, USA',
  'DoubleTree Suites by Hilton Hotel Santa Monica, 4th Street, Santa Monica, CA, USA',
  'The Hacienda at Hilton Puerto Vallarta All Inclusive Adults Only',
  'Hampton Inn Monterrey Aeropuerto',
  'Hilton Minneapolis',
  'Hilton San Diego Gaslamp Quarter',
  'Homewood Suites by Hilton San Diego Downtown',
  'Hilton Garden Inn San Diego Downtown/Bayside',
  'Hampton Inn Manhattan/Times Square Central',
  'Hampton Inn & Suites by Hilton Los Cabos',
  'Ocean Tower at Hilton Waikoloa Village Asia',
  'Hilton Garden Inn Denver Airport',
  'Hampton Inn Las Vegas/North Speedway',
  'Hampton Inn and Suites Las Vegas/West Summerlin',
  'Hampton Inn Las Vegas/Summerlin',
  'Hilton Grand Vacations on Paradise',
  'Hampton Inn Tropicana',
  'Hampton Inn and Suites Las Vegas Airport',
  'Embassy Suites by Hilton Las Vegas',
  'DoubleTree by Hilton Las Vegas Airport',
  'Embassy Suites by Hilton Convention Center Las Vegas',
  'Homewood Suites by Hilton Las Vegas Airport',
  'Hampton Inn and Suites Henderson/Saint Rose',
  'Homewood Suites by Hilton Henderson/South Las Vegas',
  'Hampton Inn and Suites Henderson',
  'Hilton Garden Inn Las Vegas/Henderson',
  'Homewood Suites by Hilton Miami Downtown/Brickell',
  'Hilton Garden Inn Valencia Six Flags',
  'DoubleTree by Hilton Hotel Bakersfield',
  'Embassy Suites by Hilton Phoenix Scottsdale',
  'Hilton Garden Inn Dallas Downtown',
  'Hilton Garden Inn New York Times Square South',
  'El Conquistador Tucson, A Hilton Resort',
  'DoubleTree by Hilton Hotel Golf Resort Palm Springs',
  'McLean/DoubleTree by Hilton',
  'DoubleTree by Hilton Nashua',
  'Hilton San Diego Airport-Harbor Island',
  'The Darcy, Curio Collection by Hilton',
  'Homewood Suites by Hilton New Orleans French Quarter',
  'Hilton Cabana Miami Beach',
  'Condado Lagoon Villas at Caribe Hilton',
  'Hilton Garden Inn Miami South Beach',
  'Hilton Mexico City Reforma',
  'Hilton Puerto Vallarta Resort',
  'Hilton Garden Inn Redondo Beach',
  'GALLERYone - a DoubleTree Suites by Hilton Hotel',
  'The Gates Hotel South Beach - A DoubleTree By Hilton',
  'Doubletree by Hilton Orlando at SeaWorld',
  'Hampton Inn International Dr Convention Center',
  'Hilton Boston Downtown-Faneuil Hall',
  'DoubleTree by Hilton Bethesda-Washington D.C.',
  'DoubleTree by Hilton Hotel Portland, ME',
  'Hilton Garden Inn New York/Tribeca',
  'Hilton Garden Inn New York/West 35th Street',
  'Hampton Inn Manhattan-Chelsea',
  'Hampton Inn Manhattan-35th St/Empire State Bldg',
  'Hampton Inn Manhattan-Seaport-Financial District',
  'DoubleTree by Hilton Hotel New York City - Chelsea',
  'Hampton Inn Manhattan Grand Central',
  'Hilton Garden Inn New York/Central Park South-Midtown West',
  'Hampton Inn Manhattan-Times Square North',
  'Hilton Garden Inn New York/Manhattan-Midtown East',
  'DoubleTree by Hilton Hotel New York - Times Square South',
  'Hampton Inn Manhattan-SoHo',
  'DoubleTree by Hilton Cape Cod - Hyannis',
  'Hilton Garden Inn Austin Downtown',
  'Hilton Garden Inn Times Square',
  'Hampton Inn Madison Square Garden',
  'Hilton Newark Penn Station ',
  'The Wit Chicago a Doubletree by Hilton',
  'DoubleTree by Hilton Del Mar',
  'Hilton Orange County',
  'Doubletree by Hilton Irvine Spectrum',
  'DoubleTree by Hilton Santa Ana Orange County Airport',
  'Hilton Phoenix Mesa',
  'Hilton Waikoloa Village Asia',
  'Hilton Marco Island Beach Resort and Spa',
  'Hilton Santa Barbara Beachfront Resort',
  'Hilton Garden Inn Carlsbad Beach',
  'Hilton Palm Springs',
  'Hilton Santa Fe at Buffalo Thunder',
  'Hilton Garden Inn Orlando International Drive North',
  'Doubletree by Hilton Fresno Convention Center',
  'Cape Rey Carlsbad, A Hilton Resort',
  'Hilton Garden Inn New York Chelsea',
  'DoubleTree by Hilton Greenway Plaza',
  'DoubleTree by Hilton Hotel Anaheim - Orange County',
  'DoubleTree by Hilton Tucson at Reid Park',
  'Hampton Inn Downtown French-Quarter Area',
  'DoubleTree by Hilton San Pedro - Port of Los Angeles',
  'Hilton Portland Downtown',
  'DoubleTree by Hilton Hotel Grand Junction',
  'Hilton Singer Island Oceanfront Palm Beaches',
  'DoubleTree by Hilton San Diego Mission Valley',
  'Doubletree by Hilton Deerfield Beach-Boca Raton',
  'Hampton Inn and Suites Convention Center ',
  'Homewood Suites by Hilton North Happy Valley',
  'Hilton Orlando Altamonte Springs',
  'Hilton Santa Cruz Scotts Valley',
  'DoubleTree by Hilton San Francisco Airport North',
  'Hilton Galveston Island Resort',
  'The Waterfront Beach Resort, a Hilton Hotel',
  'Hilton Garden Inn Waikiki Beach',
  'DoubleTree Suites by Hilton Santa Monica',
  'The Curtis - A Doubletree By Hilton',
  'Doubletree by Hilton Sonoma Wine Country',
  'Millennium Hilton New York One UN Plaza',
  'Hilton Anchorage',
  'DoubleTree Beach Resort by Hilton Tampa Bay',
  'Homewood Suites by Hilton Nearest Universal Orlando',
  'Pointe Hilton Tapatio Cliffs Resort',
  'Pointe Hilton Squaw Peak Resort',
  'Doubletree by Hilton Hotel Circle',
  'Caribe Hilton',
  'Doubletree by Hilton Hotel Baton Rouge',
  'Hilton Garden Inn New Orleans French Quarter',
  'Hilton Fort Worth ',
  'Hilton Miami Downtown',
  'Hilton Minneapolis St. Paul Airport',
  'Bahia Mar Fort Lauderdale Beach - a DoubleTree by Hilton',
  'Hilton Sonoma Wine Country',
  'Condado Plaza Hilton',
  'Millennium Hilton New York Downtown',
  'DoubleTree Resort by Hilton Hollywood Beach',
  'Westgate New York City, formerly Hilton New York Grand Central',
  'Hilton Chicago Ohare Airport',
  'Hilton West Palm Beach, Okeechobee Boulevard, West Palm Beach, FL, USA',
  'Pointe Hilton Tapatio Cliffs Resort, North 7th Street, Phoenix, AZ, USA',
  'Hilton Santa Barbara Beachfront Resort, East Cabrillo Boulevard, Santa Barbara, CA, USA',
  'Hilton Hua Hin Resort & Spa, Naresdamri Road Hua Hin, Hua Hin District, Prachuap Khiri Khan, Thailand',
  'Mahogany Bay Resort & Beach Club, Curio Collection by Hilton, San Pedro Ambergris C, Belize',
  'Hilton new york fashion districk ',
  'Embassy Suites by Hilton Napa Valley, California Boulevard, Napa, CA, USA',
  'Hampton Inn & Suites Lady Lake/The Villages, Northeast 63rd Drive, Lady Lake, FL, USA',
  'Hilton Grand Vacations at Tuscany Village, Arrezzo Way, Orlando, FL, USA',
  'Hilton Burlington, Battery Street, Burlington, VT, USA',
  'Hilton San Diego Bayfront, Park Boulevard, San Diego, CA, USA',
  'The Art Hotel Denver, Curio Collection by Hilton',
  'LondonHouse Chicago, Curio Collection by Hilton, East Upper Wacker Drive, Chicago, IL, USA',
  'Homewood Suites by Hilton Moab',
  'Inn and Club at Harbour Town, Lighthouse Lane, Hilton Head Island, SC, USA',
  'Grand Naniloa Hotel Hilo - a DoubleTree by Hilton, Banyan Drive, Hilo, HI, USA',
  'DoubleTree by Hilton Hotel Memphis Downtown, Union Avenue, Downtown, Memphis, TN, USA',
  'The Park Vista - a DoubleTree by Hilton Hotel',
  'Hampton Inn Cheyenne, Fleischli Parkway, Cheyenne, WY, USA',
  'Hilton Garden Inn Rapid City, East Mall Drive, Rapid City, SD, USA',
  'Hilton Guam Resort & Spa',
  'Hilton Guam Resort & Spa',
  'Protea Hotel by Marriott Hilton',
  'Hampton Inn, Norman Rd, Bar Harbor, ME, USA',
  'Hilton Garden Inn Kauai Wailua Bay, Kuhio Highway, Kapaa, HI, USA',
  'Hilton Lake Las Vegas Resort & Spa',
  'Hilton Garden Inn Portland Downtown Waterfront, Commercial Street, Portland, ME, United States',
  'DoubleTree by Hilton Hotel & Spa Napa Valley',
  'Hampton Inn & Suites Pocatello, Vista Drive, Pocatello, ID, United States',
  'Hampton Inn Jackson Hole, U.S. 89, Jackson, WY, United States',
  'DoubleTree Suites by Hilton Hotel Boston-Cambridge, Soldiers Field Road, Boston, MA, United States',
  'Hampton Inn Cocoa Beach/Cape Canaveral, North Atlantic Avenue, Cocoa Beach, FL, United States',
  'Hampton Inn Durango, Main Avenue, Durango, CO, United States',
  'Home2 Suites by Hilton Amarillo, West Amarillo Boulevard, Amarillo, TX, United States',
  'Hampton Inn Clinton, Kansas Avenue, Clinton, MO, United States',
  'Holiday Inn Express Hilton Head Island',
  'DoubleTree by Hilton Hotel Woking',
  'DoubleTree by Hilton Hotel Alice Springs',
  'DoubleTree by Hilton Vail',
  'DoubleTree by Hilton Hotel Darwin',
  'Hilton Garden Inn Dalton',
  'DoubleTree by Hilton Hotel Decatur Riverfront',
  'DoubleTree by Hilton Hotel Cairns',
  'Candlewood Suites Bluffton-Hilton Head',
  'Homewood Suites by Hilton Montgomery EastChase',
  'Homewood Suites by Hilton Jacksonville Deerwood Park',
  'Homewood Suites by Hilton Eatontown',
  'DoubleTree by Hilton Hotel Galveston Beach',
  'Hilton Nashville Airport',
  'DoubleTree by Hilton Atlanta Perimeter Dunwoody',
  'DoubleTree by Hilton Hotel Santa Fe',
  'DoubleTree by Hilton Hotel Schenectady',
  'Homewood Suites by Hilton Aurora Naperville',
  'Sonesta Resort Hilton Head Island',
  'Embassy Suites by Hilton West Palm Beach Central',
  'DoubleTree by Hilton Hotel Buffalo - Amherst',
  'DoubleTree by Hilton Halifax Dartmouth',
  'The Campbell House, Curio Collection by Hilton a',
  'DoubleTree by Hilton Hotel Jacksonville Riverfront a',
  'DoubleTree by Hilton Hotel Sunrise - Sawgrass Mills',
  'Hampton Inn Chicago Downtown/Magnificent Mile',
  'DoubleTree by Hilton Boston North Shore',
  'DoubleTree by Hilton Hotel Billings',
  'DoubleTree by Hilton Hotel Minneapolis North',
  'DoubleTree by Hilton Hotel Pittsburgh - Meadow Lands',
  'DoubleTree by Hilton Hotel Laurel',
  'DoubleTree by Hilton Mount Vernon',
  'DoubleTree by Hilton Hotel Lawrence',
  'DoubleTree by Hilton Hotel Richmond - Midlothian',
  'Hampton Inn Salem',
  'DoubleTree by Hilton Hotel Boston - Rockland',
  'DoubleTree by Hilton Hotel Raleigh - Brownstone - University',
  'DoubleTree by Hilton Hotel Winston Salem - University',
  'Holiday Inn Resort Beach House Hilton Head Island',
  'DoubleTree by Hilton Helena Downtown',
  'DoubleTree by Hilton Harrisonburg',
  'DoubleTree by Hilton Fort Smith City Center',
  'DoubleTree by Hilton Hotel North Charleston Convention Center',
  'Hampton Inn & Suites Buffalo Downtown',
  'DoubleTree by Hilton Baltimore BWI Airport',
  'Holiday Inn Express & Suites Hardeeville-Hilton Head',
  'Hampton Inn Covington',
  'Holiday Inn Express & Suites Bluffton @ Hilton Head Area',
  'Hilton Garden Inn Minneapolis Airport Mall of America',
  'Hilton Garden Inn San Diego Mission Valley Stadium',
  'DoubleTree by Hilton Hotel Orlando East-UCF Area',
  'DoubleTree by Hilton Hotel Orlando Airport',
  'Hilton Seychelles Labriz Resort & Spa, Silhouette, Seychelles',
  'Embassy Suites by Hilton Deerfield Beach Resort & Spa, South Ocean Drive, Deerfield Beach, FL, United States',
  'Hampton Inn & Suites Napa, Napa Valley, Hartle Court, Napa, CA, United States',
  'The Inn At Penn A Hilton Hotel',
  'Hilton Garden Inn Portsmouth Downtown, High Street, Portsmouth, NH, United States',
  'Hilton Garden Inn Guatemala City, 13 Calle, Guatemala City, Guatemala',
  'Hampton Inn Montrose, North Townsend Avenue, Montrose, CO, United States',
  'DoubleTree Resort by Hilton Central Pacific',
  'DoubleTree Suites by Hilton Hotel, Broadway, New York, NY, United States',
  'DoubleTree Suites by Hilton Hotel, Broadway, New York, NY, United States',
  'DoubleTree by Hilton Hotel Missoula - Edgewater, Madison Street, Missoula, MT, United States',
  'Hampton Inn & Suites Lake Powell',
  'DoubleTree by Hilton Cocoa Beach Oceanfront, North Atlantic Avenue, Cocoa Beach, FL, United States',
  'DoubleTree by Hilton, North Interstate Highway 35, Austin, TX, United States',
  'Hilton Hawaiian Village Waikiki Beach Resort ',
  'Capital Hilton ',
  'Hilton Garden Inn Mountain View',
  'DoubleTree by Hilton Hotel Jackson, U.S. 45 Bypass, Jackson, TN, United States',
  'Homewood Suites by Hilton Cape Canaveral-Cocoa Beach, Astronaut Boulevard, Cape Canaveral, FL, United States',
  'DoubleTree by Hilton Hotel Lafayette, West Pinhook Road, Lafayette, LA, United States',
  'Hilton Midtown, 6th Avenue, New York, NY, United States',
  'Jewel Dunns River Beach Resort & Spa, Ocho Rios, Curio Collection by Hilton, St. Ann Parish, Jamaica',
  'Doubletree Resort by Hilton Hotel Alana Waikiki Beach',
  'The Highland Dallas, Curio Collection by Hilton',
  'Parc Soleil by Hilton Grand Vacations, Desforges Avenue, Orlando, FL, United States',
  'Homewood Suites by Hilton Charleston',
  'Homewood Suites by Hilton Orlando-Maitland',
  'DoubleTree Suites by Hilton Hotel New York City ',
  'DoubleTree by Hilton Hotel at the Entrance to Universal Orlando',
  'Hilton Garden Inn Bloomington',
  'Hampton Inn & Suites Page - Lake Powell, Page, AZ, United States',
  'The Logan Philadelphia, Curio Collection by Hilton',
  'Hilton at Resorts World Bimini',
  'Hampton Inn Houma',
  'Hilton Garden Inn Clovis',
  'Hilton Garden Inn San Jose La Sabana',
  'Hilton Waikiki Beach, Kuhio Avenue, Honolulu, HI, United States',
  'Double Tree by Hilton Marina del Rey',
  'Hilton Oakland Airport',
  'DoubleTree by Hilton Denver',
  'Hilton Vancouver Airport, Minoru Boulevard, Richmond, BC, Canada',
  'Hampton Inn & Suites Arroyo Grande/Pismo Beach Area, West Branch Street, Arroyo Grande, CA, United States',
  'Homewood Suites by Hilton Kalispell, MT, Hutton Ranch Road, Kalispell, MT, United States',
  'Hilton Garden Inn Augusta',
  'Embassy Suites by Hilton Boca Raton',
  'Hampton Inn Buffalo South/I-90',
  'Hampton Inn & Suites Springdale/Zion National Park',
  'Omni Hilton Head Oceanfront Resort',
  'Hilton Auckland, Quay Street, Auckland, New Zealand',
  'Hilton Garden Inn Flagstaff',
  'Pensacola Beach Hotel Hilton',
  'The Skirvin Hilton',
  'Hilton Garden Inn Lafayette/Cajundome',
  'Doubletree by Hilton Flagstaff',
  'Hilton Garden Inn Oklahoma City Midtown',
  'DoubleTree by Hilton Toronto Downtown',
  'DoubleTree by Hilton Hotel Seattle Airport',
  'Hilton Garden Inn Key West',
  'DoubleTree by Hilton Hotel Bethesda',
  'Hilton Garden Inn Ogden',
  'Hampton Inn Clemson-University Area',
  'DoubleTree by Hilton Hotel Sunrise',
  'Hilton Garden Inn Idaho Falls',
  'Hilton Garden Inn Amarillo',
  'Homewood Suites by Hilton Medford',
  'Hampton Inn & Suites Ridgecrest',
  'London Hilton on Park Lane',
  'Hilton Garden Inn Knoxville/University',
  'Hilton Orlando Buena VIsta Palace',
  'Hilton Pyramids Golf Resort',
  'Doubletree Suites By Hilton Naples',
  'The Fess Parker A Doubletree by Hilton Resort',
  'DoubleTree by Hilton Hotel Dallas - Farmers Branch',
  'Hilton Checkers Los Angeles',
  'DoubleTree by Hilton New York - Financial District',
  'Hampton Inn Dayton/Fairborn',
  'Hampton Inn Manhattan-SoHo',
  'Hilton Garden Inn Los Angeles Hollywood',
  'Hilton Doha',
  'Hilton Jumeirah Resort',
  'Hilton Universal City',
  'Hampton Inn and Suite Rock Springs',
  'Hampton Inn & Suites Plymouth',
  'DoubleTree by Hilton Boston Downtown',
  'Hilton - Naples',
  'Hilton Garden Inn Sarasota',
  'The Quin Central Park by Hilton Club',
  'Hilton Seattle',
  'DoubleTree Resort by Hilton Paradise Valley',
  'Hampton Inn & Suite',
  'Hilton Garden Inn Missoula',
  'Hilton Anaheim',
  'Hilton Grand Vacations Suites at SeaWorld',
  'DoubleTree by Hilton Breckenridge',
  'Hilton Los Angeles Universal City',
  'Hampton Inn Lake Havasu City',
  'Hampton Inn & Suites Natchez',
  'Hampton Inn & Suites Vicksburg',
  'Hilton Garden Inn Chattanooga',
  'DoubleTree by Hilton Hotel JFK Airport',
  'Hilton Rose Hall Resort & Spa',
  'DoubleTree by Hilton Orlando Downtown',
  'Hampton Inn',
  'Hampton Inn',
  'Hilton Portland and Executive Tower',
  'Hilton New York JFK Airport Hotel',
  'Hampton Inn ',
  'Hilton Garden Inn',
  'Hilton Budapest',
  'Hilton Garden Inn Fort Myers',
  'Hampton Inn And Suites Bakersfield',
  'Hilton Niagara Falls/Fallsview',
  'Hilton Garden Inn Eden Prairie',
  'Hampton Inn and Suites Jackson-Coliseum',
  'DoubleTree by Hilton Memphis',
  'Hampton Inn Champaign Urbana',
  'Hilton Dallas Lincoln Centre',
  'Hilton Garden Inn Orlando',
  'Hilton Waikiki Beach',
  'Hilton Grand Vacations Suites on International Drive',
  'Hampton Inn & Suites Flagstaff',
  'Hampton Inn Albuquerque University/Midtown',
  'Hampton Inn Santa Fe',
  'DoubleTree by Hilton Hotel Springfield',
  'Hilton Grand Vacation Suites Las Vegas',
  'Hilton Washington',
  'Hilton Santa Fe Historic Plaza',
  'Hampton Inn Bloomington West',
  'Hilton Fort Lauderdale Marina',
  'Hilton Garden Inn Savannah Historic District',
  'Hilton Orlando Lake Buena Vista',
  'Hilton Hawaiian Village Waikiki Beach Resort',
  'Hilton Boston Back Bay',
  'Hilton Garden Inn Calgary Airport',
  'Hampton Inn & Suites Tarpon Springs',
  'Hampton Inn Okeechobee',
  'Hilton Orlando',
  'Hilton Cincinnati Netherland Plaza',
  'Hilton Parc 55 San Francisco',
  'Hilton Garden Inn Calabasas',
  'Hilton Los Angeles North Glendale',
  'Hilton Quebec',
  'Hilton Mexico City Airport',
  'Molino Stucky Hilton',
  'Hilton Longboat Key Beachfront Resort',
  'Hilton Lac-Leamy',
  'Hilton Garden Inn Billings',
  'Hilton Garden Inn Monterey',
  'Hilton San Diego Resort and Spa',
  'Hilton Key Largo Resort',
  'Hilton Sedona Resort and Spa',
  'Hilton Garden Inn Freeport Downtown',
  'Hilton Woodland Hills Los Angeles',
  'Hilton Woodland Hills Los Angeles',
  'Hilton Houston Plaza / Medical Center',
  'Hilton Fort Collins',
  'Hilton Garden Inn Montreal Centre-Ville',
  'Hilton Montreal Bonaventure',
  'Hampton Inn & Suites Boston Crosstown Center',
  'Hilton Giardini Naxos',
  'Hampton Inn St. Simons Island',
  'Homewood Suites by Hilton Rock Springs',
  'Hilton Garden Inn Bozeman',
  'Hilton Raleigh-Durham Airport',
  'Hilton Boston Logan Airport',
  'Hampton Inn Helena',
  'Hampton Inn Salt Lake City - Downtown',
  'Cliffrose Springdale, Curio Collection by Hilton',
  'Homewood Suites by Hilton Jackson',
  'Signia by Hilton Orlando Bonnet Creek',
  'Hilton Chicago O hare',
  'Hilton Daytona Beach Oceanfront Resort',
  'Hilton Americas Houston',
  'Hampton Inn Lancaster',
  'Hilton Cocoa Beach',
  'Hotel del Coronado, Curio Collection by Hilton',
  'Hilton Vancouver Metrotown',
  'Hilton Fort Lauderdale Beach Resort',
  'Hilton Salt lake City Center',
  'Hilton Boston Financial District',
  'Hilton San Francisco Financial District',
  'Hilton Clearwater Beach Resort',
  'Hilton Las Vegas',
  'Hampton Inn Kayenta',
  'Westin Hilton Head',
  'Hilton Anatole',
  'Hilton La Jolla',
  'Hilton Bentley South Beach',
  'Hilton Los Cabos',
  'Hilton Cancun Golf & Spa Resort',
  'Canoa ( Coral by Hilton )',
  'Marien ( Coral by Hilton )',
  'Hilton Dubai Creek',
  'Hilton Waikoloa Village',
  'Hilton Walt Disney Resort',
  'Hilton San Francisco Union Square',
  'Hilton Times Square',
  'Hilton Los Angeles Airport',
  'Hilton Seychelles Northolme Spa',
  'Hilton Paris Aeroport Orly',
  'Hilton Paris La Defense',
  'Hilton Paris',
  'Hilton Arc de Triomphe',
  'Palmer House Hilton',
  'Hilton Chicago',
  'Millennium Hilton',
  'Hilton New York',
  'British Colonial Hilton',
  'Hilton Mauritius',
  'Hilton Miami Airport',
  'Beverly Hilton',
]

let parsedFilteredDashboardHiltonList = [];
// let filteredDashboardHiltonList = [];
let hiltonHotelNames = [];
let hiltonRefugees = [];
let hamptons = [];
let missingHotels = [];
let others = [];
let duplicates = [];
let hello = [];
let counter = 0;
let uncounter = 0;

console.log('TOTAL LIST FROM DASHBOARD INCLUDING HILTON AND HAMPTON INN : ', hiltonList.length);
filteredDashboardHiltonList.map(hotel => {
  parsedFilteredDashboardHiltonList.push(hotel.toLowerCase());
})


Hotels.map(hotel => {


  if(hotel.hotelName){
    hiltonHotelNames.push(hotel.hotelName)
  }else{
    console.log('UNDEFINED ::: ', hotel.hotelName);
  }
  // if (hotel.hotelName) {
  //   let currentHotel = hotel.hotelName.toLowerCase();

  //   if (!parsedFilteredDashboardHiltonList.includes(currentHotel)) {
  //     return hiltonHotelNames.push(hotel.hotelName);
  //   } else {
  //     console.log('dup dupppp :::::::::: ', hotel.hotelName);

  //     duplicates.push(hotel.hotelName);

  //     counter++
  //   }





  //   if(parsedFilteredDashboardHiltonList.includes(currentHotel)){
  //     return hello.push(currentHotel)
  //   }
  // } else {
  //   console.log('UNDIFINED :: ', hotel.hotelName)
  //   uncounter++
  //   missingHotels.push(hotel.hotelName)
  // }


  // if (hotel.hotelName && !filteredDashboardHiltonList.includes(hotel.hotelName)) {

  //   return hiltonHotelNames.push(hotel.hotelName);
  //   //   filteredDashboardHiltonList.filter(function(value, index, arr){ 
  //   //     console.log('ENTRO ');
  //   //     console.log(value);
  //   //     console.log('hotel name ::: ', hotel.hotelName)
  //   //     return value == hotel.hotelName;
  //   // });

  // } else {
  //   console.log('CURRENT HOTEL : ', hotel.hotelName);
  //   if (hotel.hotelName) {
  //     console.log('dup dupppp :::::::::: ', hotel.hotelName);

  //     duplicates.push(hotel.hotelName);

  //     counter++
  //   }

  //   if (!hotel.hotelName) {
  //     console.log('UNDIFINED :: ', hotel.hotelName)
  //     uncounter++
  //   }


  //   // console.log('MISSING HOTEL ::::::::::::::::::::: ', hotel.hotelName);
  //   missingHotels.push(hotel.hotelName)



  //   return;
  // }





  // if (hotel.hotelName && hotel.hotelName.includes("Hilton")) {
  //     if (hiltonList.includes(hotel.hotelName)) {
  //       console.log('dup dup :::',hotel.hotelName);
  //       counter++;
  //     } else {
  //       hiltonHotelNames.push(hotel.hotelName);
  //     }

  //   } else {
  //     if (hotel.hotelName && hotel.hotelName.includes("Hampton")) {
  //       hamptons.push(hotel.hotelName);
  //     } else {
  //       if (hotel.hotelName) {
  //         others.push(hotel.hotelName)
  //       }

  //     }

  //     hiltonRefugees.push(hotel.hotelName);
  //   }

});

function filterItems(arr, query) {
  return arr.filter(function (el) {
    return el.toLowerCase().indexOf(query.toLowerCase()) !== -1
  })
}

/* GET home page. */
router.get('/', (req, res, next) => {

  // hiltonList.map(hotel => {
  //   if(hiltonHotelNames.includes(hotel)){
  //     console.log('yeapppp ::::::::::', hotel)
  //     counter++;
  //     filterItems(hiltonHotelNames, hotel)
  //   }else{

  //   }
  // })

  // hiltonHotelNames.map(hotel => {
  //   if(hiltonList.includes(hotel)){

  //   }
  // })
 
  let dashboardWithoutDup =  [...new Set(parsedFilteredDashboardHiltonList)];
  console.log('Dashboard filtered list ::::: ', dashboardWithoutDup.length)
  console.log('THE TOTAL AMOUNT OF DASHBOARD HOTELS THAT WERE IN THE DERBY HOTEL LIST ARE ::::: ', counter)
  console.log('THE TOTAL AMOUNT OF UNDEFINED HOTELS ON DERBYS LIST IS :::::: ', uncounter);
  // console.log('MISSING HOTEL LIST COUNT : ',  missingHotels );
  // console.log('DUPLICATES LIST  IS  : ', duplicates);
  console.log('THE DUPLICATES LIST TOTAL AT : ', duplicates.length);

  //REMOVE DUPLICATE FUNCTION
  // function removeDuplicates(array) {
  //   const result = [];
  //   for (let i = 0; i < array.length; i++) {
  //     let exists = false;
  //     for (j = 0; j < result.length; j++) {
  //       if (array[i] === result[j]) {
  //         exists = true;
  //         break;
  //       }
  //     }
  //     if (!exists) {
  //       result.push(array[i]);
  //     }
  //   }
  //   return result;
  // }


// let finally = hiltonHotelNames.filter(val => !parsedFilteredDashboardHiltonList.includes(val));


  let result = hiltonHotelNames.filter(val => !parsedFilteredDashboardHiltonList.includes(val));
  
  let comparison = parsedFilteredDashboardHiltonList.filter(val => !hiltonHotelNames.includes(val));

let finalz = hiltonHotelNames.filter(val => !comparison.includes(val));



  console.log('THE FINAL COMPARISON ::::: ', comparison.length);
console.log('SHIT SHIT HI :::  ', finalz.length)
  // let final = [...new Set(result)];
  // console.log('THE FINAL REUSLT :::: ', final.length)
  // console.log('THE MISSING HOTELLSL : ', missingHotels)
  // console.log('RANDOM RANDOM : ', hello.l)
  res.status(200).json(hiltonHotelNames);
});

router.get('/ref', (req, res, next) => {

  res.status(200).json(hiltonRefugees);
});


router.get('/hamptons', (req, res, next) => {
  res.status(200).json(hamptons)
});

router.get('/others', (req, res, next) => {
  res.status(200).json(others)
});

module.exports = router;
